name: AP_FOUNDATION_MODEL
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - h5py
  - matplotlib
  - python-dotenv
  - jupyterlab
  - ipykernel
  - pip:
      - brian2

